# This is a basic workflow to help you get started with Actions

name: Release Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - 'v*'
    branches:
      - 'release'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/wails
        with:
          build-name: editai
          build-platform: linux/amd64
          wails-version: "v2.9.2"
          package: true
          build: true
          wails-build-webview2: "embed"
          go-version: ^1.22

  macos:
    runs-on: macos-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/wails
        with:
          build-name: editai
          build-platform: darwin/universal
          wails-version: "v2.9.2"
          package: true
          build: true
          go-version: ^1.22

  windows:
    runs-on: windows-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/wails
        with:
          build-name: editai.exe
          build-platform: windows/amd64
          wails-version: "v2.9.2"
          package: true
          build: true
          nsis: true
          wails-build-webview2: "embed"
          go-version: ^1.22
