# This is a basic workflow to help you get started with Actions

name: Release Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for tags
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  packages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/wails
        with:
          build-name: editai
          build-platform: linux/amd64
          wails-version: "v2.9.2"
          package: true
          build: true
          wails-build-webview2: "embed"
          go-version: ^1.22
      - name: Rename artifact
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          mv build/bin/editai "build/bin/editai-${VERSION}-linux-amd64"
      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: "build/bin/editai-*-linux-amd64"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    runs-on: macos-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/wails
        with:
          build-name: editai
          build-platform: darwin/universal
          wails-version: "v2.9.2"
          package: true
          build: true
          go-version: ^1.22
      - name: Package macOS artifacts
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          cd build/bin
          mv editai.app "editai-${VERSION}-mac.app"
          zip -r "editai-${VERSION}-mac.app.zip" "editai-${VERSION}-mac.app"
          mv editai.pkg "editai-${VERSION}-mac.pkg"
      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/bin/editai-*-mac.app.zip
            build/bin/editai-*-mac.pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    runs-on: windows-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/wails
        with:
          build-name: editai
          build-platform: windows/amd64
          wails-version: "v2.9.2"
          package: true
          build: true
          nsis: true
          wails-build-webview2: "embed"
          go-version: ^1.22
      - name: Rename artifacts
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          cd build/bin
          mv editai.exe "editai-${VERSION}-windows-amd64-portable.exe"
          mv editai-installer.exe "editai-${VERSION}-windows-amd64-installer.exe"
      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/bin/editai-*-windows-amd64-portable.exe
            build/bin/editai-*-windows-amd64-installer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
